#Will start the gateway server @8180
server:
  port: 8180

spring:
  application:
    name: gateway-service

# Disable accessing services using service name (i:e: user-service):
# They should be only accessed through the path defined below:
zuul:
  ignored-services: "*"
  # Map paths to auth service
  routes:
    auth-service:
      path: /auth-api/**
      serviceId: auth-service
      stripPrefix: false
    product-service:
      path: /product-api/**
      serviceId: product-service
      stripPrefix: false
    delivery-service:
      path: /delivery-api/**
      serviceId: delivery-service
      stripPrefix: false
    sales-service:
      path: /delivery-api/**
      serviceId: delivery-service
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2

ribbon:
  eager-load:
    enabled: true
